In [59]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("uciml/glass")

print("Path to dataset files:", path)

c:\Users\BM MONEY\miniconda3\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


Path to dataset files: C:\Users\BM MONEY\.cache\kagglehub\datasets\uciml\glass\versions\1


In [60]:
import os 
import pandas as pd

os.listdir(path)
data_path = os.path.join(path, 'glass.csv')

df = pd.read_csv(data_path)
df.head().style.background_gradient(cmap = 'Blues', axis = 0)

In [2]:
df['Type'].unique()

array([1, 2, 3, 5, 6, 7], dtype=int64)

In [3]:
df.describe().T

count       mean       std       min        25%       50%        75%  \
RI    214.0   1.518365  0.003037   1.51115   1.516522   1.51768   1.519157   
Na    214.0  13.407850  0.816604  10.73000  12.907500  13.30000  13.825000   
Mg    214.0   2.684533  1.442408   0.00000   2.115000   3.48000   3.600000   
Al    214.0   1.444907  0.499270   0.29000   1.190000   1.36000   1.630000   
Si    214.0  72.650935  0.774546  69.81000  72.280000  72.79000  73.087500   
K     214.0   0.497056  0.652192   0.00000   0.122500   0.55500   0.610000   
Ca    214.0   8.956963  1.423153   5.43000   8.240000   8.60000   9.172500   
Ba    214.0   0.175047  0.497219   0.00000   0.000000   0.00000   0.000000   
Fe    214.0   0.057009  0.097439   0.00000   0.000000   0.00000   0.100000   
Type  214.0   2.780374  2.103739   1.00000   1.000000   2.00000   3.000000   

           max  
RI     1.53393  
Na    17.38000  
Mg     4.49000  
Al     3.50000  
Si    75.41000  
K      6.21000  
Ca    16.19000  
Ba     3.15000  
Fe     0.51000  
Type   7.00000

In [4]:
from sklearn.model_selection import train_test_split

X = df.drop(columns='Type')
y = df['Type']

In [5]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

In [6]:
X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.3, random_state=42)

1. Feature Extraction with ANN + Classification with SVM


In [7]:
import tensorflow as tf

In [8]:
d_in = (X_train.shape[1],)

input_layer = tf.keras.Input(shape=d_in)
x = tf.keras.layers.Dense(128, activation='relu', kernel_regularizer=
                          tf.keras.regularizers.l2(0.01))(input_layer)
x = tf.keras.layers.BatchNormalization()(x)
x = tf.keras.layers.Dropout(0.5)(x)
x = tf.keras.layers.Dense(64, activation='relu', kernel_regularizer=
                          tf.keras.regularizers.l2(0.01))(x)
output_layer = tf.keras.layers.Dense(X_train.shape[1])(x)
model = tf.keras.Model(inputs=input_layer, outputs=output_layer)

model.compile(optimizer=tf.keras.optimizers.Adam(learning_rate=1e-2), metrics=['accuracy'], loss='mse')

In [9]:
model.summary()

Model: "functional_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ input_layer (InputLayer)        │ (None, 9)              │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ (None, 128)            │         1,280 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ batch_normalization             │ (None, 128)            │           512 │
│ (BatchNormalization)            │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout (Dropout)               │ (None, 128)            │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 64)             │         8,256 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 9)              │           585 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 10,633 (41.54 KB)

 Trainable params: 10,377 (40.54 KB)

 Non-trainable params: 256 (1.00 KB)

In [10]:
history = model.fit(X_train, X_train, epochs=50, batch_size=64, validation_split=0.2, verbose=1)

Epoch 1/50
2/2 ━━━━━━━━━━━━━━━━━━━━ 2s 382ms/step - accuracy: 0.1489 - loss: 4.3415 - val_accuracy: 0.4000 - val_loss: 1.9281
Epoch 2/50
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step - accuracy: 0.5408 - loss: 2.5308 - val_accuracy: 0.2000 - val_loss: 1.8249
Epoch 3/50
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - accuracy: 0.5028 - loss: 2.1095 - val_accuracy: 0.1667 - val_loss: 1.8197
Epoch 4/50
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - accuracy: 0.3975 - loss: 1.8765 - val_accuracy: 0.1667 - val_loss: 1.8063
Epoch 5/50
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.4808 - loss: 1.6476 - val_accuracy: 0.1667 - val_loss: 1.7723
Epoch 6/50
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step - accuracy: 0.4644 - loss: 1.6661 - val_accuracy: 0.2333 - val_loss: 1.7315
Epoch 7/50
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 0.5412 - loss: 1.4097 - val_accuracy: 0.3000 - val_loss: 1.6950
Epoch 8/50
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 0.5584 - loss: 1.3087 - val_accuracy: 0.3333 - val_loss: 1.6719

In [11]:
loss, accuracy = model.evaluate(X_train, X_train)

print(f'Loss: {loss}')
print(f'Accuracy: {accuracy}')

5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8033 - loss: 0.7634 
Loss: 0.8500337600708008
Accuracy: 0.7718120813369751


In [12]:
model.layers[-2].output

<KerasTensor shape=(None, 64), dtype=float32, sparse=False, name=keras_tensor_4>

In [13]:
feature_extractor = tf.keras.Model(inputs=model.input, outputs=model.layers[-2].output) 

In [14]:
X_train_features = feature_extractor.predict(X_train)
X_test_features = feature_extractor.predict(X_test)

5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step 


In [15]:
from sklearn.svm import SVC
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

svm = SVC(kernel='rbf', C=1, gamma=1, probability=True)
svm.fit(X_train_features, y_train)

SVC(C=1, gamma=1, probability=True)

In [16]:
y_prob = svm.predict_proba(X_test_features)
y_prob.round()

array([[0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1.],
       [0., 1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 1.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [1., 0., 0., 0., 0., 0.],
       [0.

In [17]:
y_pred = svm.predict(X_test_features)
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           1       0.87      0.68      0.76        19
           2       0.59      0.96      0.73        23
           3       0.00      0.00      0.00         4
           5       1.00      0.33      0.50         6
           6       1.00      0.67      0.80         3
           7       1.00      0.90      0.95        10

    accuracy                           0.74        65
   macro avg       0.74      0.59      0.62        65
weighted avg       0.76      0.74      0.71        65



c:\Users\BM MONEY\miniconda3\Lib\site-packages\sklearn\metrics\_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Users\BM MONEY\miniconda3\Lib\site-packages\sklearn\metrics\_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Users\BM MONEY\miniconda3\Lib\site-packages\sklearn\metrics\_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [18]:
acc_1 = accuracy_score(y_test, y_pred)
acc_1

0.7384615384615385

In [19]:
confusion_matrix(y_test, y_pred)

array([[13,  6,  0,  0,  0,  0],
       [ 1, 22,  0,  0,  0,  0],
       [ 1,  3,  0,  0,  0,  0],
       [ 0,  4,  0,  2,  0,  0],
       [ 0,  1,  0,  0,  2,  0],
       [ 0,  1,  0,  0,  0,  9]], dtype=int64)

2. ANN Classification + SVM Refinement


In [20]:
y_train_encoded = tf.keras.utils.to_categorical(y_train - 1, num_classes=7)
y_test_encoded = tf.keras.utils.to_categorical(y_test - 1, num_classes=7)

In [23]:
d_in = X_train.shape[1]
model2 = tf.keras.Sequential([
    tf.keras.layers.Dense(128, activation='relu',
                          kernel_regularizer=tf.keras.regularizers.l2(0.01), input_dim=d_in),
    tf.keras.layers.BatchNormalization(),
    tf.keras.layers.Dropout(0.25),
    tf.keras.layers.Dense(64, activation='relu',
                          kernel_regularizer=tf.keras.regularizers.l2(0.01)),
    tf.keras.layers.BatchNormalization(),
    tf.keras.layers.Dropout(0.25),
    tf.keras.layers.Dense(7, activation='softmax')
])

model2.compile(optimizer=tf.keras.optimizers.Adam(learning_rate=1e-2), 
               loss='categorical_crossentropy', metrics=['accuracy'])

In [24]:
history2 = model2.fit(X_train, y_train_encoded, epochs=50, batch_size=64, validation_split=0.2, verbose=1)

Epoch 1/50
2/2 ━━━━━━━━━━━━━━━━━━━━ 3s 460ms/step - accuracy: 0.1821 - loss: 3.4664 - val_accuracy: 0.5000 - val_loss: 2.6834
Epoch 2/50
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - accuracy: 0.6393 - loss: 2.2970 - val_accuracy: 0.5333 - val_loss: 2.5057
Epoch 3/50
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - accuracy: 0.7594 - loss: 1.8658 - val_accuracy: 0.6000 - val_loss: 2.3897
Epoch 4/50
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - accuracy: 0.7702 - loss: 1.7419 - val_accuracy: 0.6000 - val_loss: 2.3010
Epoch 5/50
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - accuracy: 0.7874 - loss: 1.6045 - val_accuracy: 0.5667 - val_loss: 2.2356
Epoch 6/50
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 0.7930 - loss: 1.5311 - val_accuracy: 0.5000 - val_loss: 2.1918
Epoch 7/50
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 0.7874 - loss: 1.4358 - val_accuracy: 0.5000 - val_loss: 2.1522
Epoch 8/50
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - accuracy: 0.8030 - loss: 1.4309 - val_accuracy: 0.5000 - val_loss: 2.1126

In [28]:
loss, accuracy = model2.evaluate(X_test, y_test_encoded)

print(f'Loss: {loss}')
print(f'Accuracy: {accuracy}')

3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 509us/step - accuracy: 0.3565 - loss: 1.9102
Loss: 2.177774667739868
Accuracy: 0.3692307770252228


In [29]:
import numpy as np

In [30]:
y_pred_proba = model2.predict(X_test)
y_pred_ann= np.argmax(y_pred_proba, axis=1)

3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step


In [33]:
threshold = 0.5
uncertain_values = np.max(y_pred_proba, axis=1) < threshold
certain_values = np.logical_not(uncertain_values)

f_predictions = y_pred_ann.copy()

In [34]:
y_train_decoded = np.argmax(y_train_encoded, axis=1) + 1
y_test_decoded = np.argmax(y_test_encoded, axis=1) + 1

In [54]:
svm2 = SVC(kernel='rbf' ,C=1, probability=True)
svm2.fit(X_train, y_train_decoded)

if np.sum(uncertain_values) > 0:
    f_predictions[uncertain_values] = svm2.predict(X_test[uncertain_values])

print(classification_report(y_test_decoded, f_predictions))

              precision    recall  f1-score   support

           0       0.00      0.00      0.00         0
           1       0.00      0.00      0.00        19
           2       0.67      0.43      0.53        23
           3       0.00      0.00      0.00         4
           4       0.00      0.00      0.00         0
           5       1.00      0.33      0.50         6
           6       0.67      0.67      0.67         3
           7       1.00      0.90      0.95        10

    accuracy                           0.35        65
   macro avg       0.42      0.29      0.33        65
weighted avg       0.51      0.35      0.41        65



c:\Users\BM MONEY\miniconda3\Lib\site-packages\sklearn\metrics\_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Users\BM MONEY\miniconda3\Lib\site-packages\sklearn\metrics\_classification.py:1471: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Users\BM MONEY\miniconda3\Lib\site-packages\sklearn\metrics\_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Users\BM MONEY\miniconda3\Lib\site-packages\skle

In [55]:
acc_2 = accuracy_score(y_test, f_predictions)
acc_2

0.35384615384615387

In [56]:
conf = confusion_matrix(y_test, f_predictions)
conf

array([[ 0,  0,  0,  0,  0,  0,  0,  0],
       [18,  0,  1,  0,  0,  0,  0,  0],
       [11,  2, 10,  0,  0,  0,  0,  0],
       [ 3,  0,  1,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  3,  0,  1,  2,  0,  0],
       [ 1,  0,  0,  0,  0,  0,  2,  0],
       [ 0,  0,  0,  0,  0,  0,  1,  9]], dtype=int64)

Accuracy Processing 1 and 2

In [57]:
acc_1, acc_2

(0.7384615384615385, 0.35384615384615387)